--SELECT 
--    PRODUCT_NO,
--    PRODUCT_NAME,
--    PRICE,
--    PRODUCT_CATEGORY,
----    STAR,
----    COUNT(REVIEW_NO) AS REVIEW_COUNT,
--    FILE_PATH || CHANGE_NAME AS PRODUCT_IMG
--FROM PRODUCT P
--JOIN ATTACHMENT_PRODUCT ON (P.PRODUCT_NO = REF_PNO)
--JOIN REVIEW R USING(PRODUCT_NO)
--WHERE P.STATUS = 'Y'
--  AND FILE_LEVEL = 1
--GROUP BY PRODUCT_NO, 
--         PRODUCT_NAME, 
--         PRICE, 
--         PRODUCT_CATEGORY, 
--         STAR, 
--         FILE_PATH, 
--         CHANGE_NAME
--ORDER BY PRODUCT_NO DESC;

SELECT PRODUCT_NO,
       PRODUCT_NAME,
       PRICE,
       PRODUCT_CATEGORY,
       STAR,
       COUNT(REVIEW_NO) AS "REVIEW_COUNT",
       FILE_PATH || CHANGE_NAME AS "PRODUCT_IMG"
  FROM PRODUCT P
  JOIN ATTACHMENT_PRODUCT ON (PRODUCT_NO = REF_PNO)
  LEFT JOIN REVIEW R USING(PRODUCT_NO)
 WHERE P.STATUS = 'Y'
   AND FILE_LEVEL = 1
   GROUP BY PRODUCT_NO, 
         PRODUCT_NAME, 
         PRICE, 
         PRODUCT_CATEGORY, 
         STAR, 
         FILE_PATH, 
         CHANGE_NAME
 ORDER BY PRODUCT_NO DESC