    	SELECT S.BOARD_NO,
    		   MEMBER_ID,
    		   BOARD_TITLE,
    		   BOARD_DETAIL,
    		   BOARD_DATE,
    		   BOARD_VIEWS,
    		   PLACE,
    		   FIND_DATE,
    		   S.TYPE,
    		   FILE_PATH || CHANGE_NAME AS "TITLE_IMG"
    	  FROM SALE_MISSING S
    	  JOIN MEMBER USING (MEMBER_ID)
    	  JOIN ATTACHMENT_ADOPT ON (REF_ANO = BOARD_NO)
    	 WHERE S.TYPE = 'A'
    	 ORDER BY S.BOARD_NO DESC